---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 31726
    name: external-port
  - port: 9093
    targetPort: 9093
    name: internal-port
  selector:
    app: kafka-deploy
    type: kafka
    id: "0"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka-deploy
        type: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka-deploy
        type: kafka
        id: "0"
    spec:
      containers:
      - name: kafka-container
        image: confluentinc/cp-kafka:5.5.1
        ports:
        - containerPort: 9092
          name: external-port
        - containerPort: 9093
          name: internal-port
        env:
#LISTENERS are what interfaces Kafka binds to. 
#ADVERTISED_LISTENERS are how clients can connect.        
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENERS
          value: INTERNAL://:9093,EXTERNAL://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://localhost:9093,EXTERNAL://localhost:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"