---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-deploy
    type: kafka
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka-deploy
        type: kafka
  template:
    metadata:
      labels:
        app: kafka-deploy
        type: kafka
    spec:
      containers:
      - name: kafka-container
        image: confluentinc/cp-kafka:5.5.1
        ports:
        - containerPort: 9092
        env:
#        - name: KAFKA_ADVERTISED_PORT
#          value: "30718"
#        - name: KAFKA_ADVERTISED_HOST_NAME
#          value: 192.168.1.240
#        - name: KAFKA_BROKER_ID
#          value: "1"
#        - name: KAFKA_CREATE_TOPICS
#          value: words:1:1    # Topic words with 1 partition and 1 replica
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"